# Generated by Django 3.1.2 on 2020-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trt_lot_no', models.CharField(max_length=200)),
                ('prt_lot_no', models.CharField(max_length=200)),
                ('treat_mch_no', models.CharField(max_length=200)),
                ('treat_trt_uptime', models.IntegerField()),
                ('print_mch_no', models.CharField(max_length=200)),
                ('print_prt_uptime', models.IntegerField()),
                ('print_raw_mat', models.CharField(max_length=200)),
                ('print_dry_no', models.CharField(max_length=200)),
                ('print_heat_treat', models.CharField(max_length=200)),
                ('print_prd_type', models.CharField(max_length=200)),
                ('mold_snd_mch_no', models.CharField(max_length=200)),
                ('mold_snd_uptime', models.IntegerField()),
                ('mold_snd_raw_mat', models.CharField(max_length=200)),
                ('mold_snd_dry_no', models.CharField(max_length=200)),
                ('mold_snd_heat', models.CharField(max_length=200)),
                ('material_cd_no', models.CharField(max_length=200)),
                ('material_mat_nm', models.CharField(max_length=200)),
                ('material_mat_emit_no', models.CharField(max_length=200)),
            ],
        ),
    ]
